{{- if and (not .Values.pythonApi.existingSecret) .Values.pythonApi.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "malsori.pythonSecretName" . }}
  labels:
    {{- include "malsori.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.pythonApi.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
