apiVersion: v1
kind: Service
metadata:
  name: {{ include "malsori.fullname" . }}
  labels:
    {{- include "malsori.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "malsori.selectorLabels" . | nindent 4 }}
  ports:
    - name: python
      port: {{ .Values.service.pythonPort }}
      targetPort: python
    - name: web
      port: {{ .Values.service.webPort }}
      targetPort: web
